/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 logo.glb -T 
Files: logo.glb [12.01KB] > logo-transformed.glb [2.04KB] (83%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/logo-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <meshBasicMaterial color={0x000fff} />
      <mesh geometry={nodes.Cube001.geometry} material={materials.Material} position={[0.176, -1.41, 0]} rotation={[0, 1.553, -1.574]} scale={[1, 0.414, 1]} />
    </group>
  )
}

useGLTF.preload('/logo-transformed.glb')
